# MCU name
MCU = STM32F411
##BOARD = GENERIC_STM32_F411XE
BOARD = BONSAI_C4
# Bootloader selection
BOOTLOADER = stm32-dfu

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = WS2812
WS2812_DRIVER = pwm

EEPROM_DRIVER = spi

CONSOLE_ENABLE = yes